baseURL = "https://imonthercks.github.io/reese-power/"
languageCode = "en-us"
title = "Reese Power"
theme = "osprey"

[Params]
  tagline = "Coming soon..."
  logoBig = "/images/reese power2.png"
  customCSS = false