title = "Reese Power"
baseURL = "https://reese-power.com/"
tags = ["portfolio"]
languageCode = "en-us"
config = "config.toml"
theme = "reesepower"
canonifyURLS = true
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies
publishDir = "docs"


[Params]
  tagline = "Choose JOY!"
  logoBig = "/images/reese power2.png"
  logoSmall = "/images/reese power2.png"
  customCSS = false

  # Choose either Formspree contact form or Basin contact form
  ajaxBasin = "https://usebasin.com/f/fb09bd68fea8"

[[menu.main]]
  name = "Donate"
  url  = "/#teammate"
  weight = 1  

[[menu.main]]
  name = "Gallery"
  url  = "/#gallery"
  weight = 2  

[[menu.main]]
  name = "Events"
  url  = "/#event"
  weight = 3  

[[menu.main]]
  name = "Contact"
  url  = "/#contact"
  weight = 4